"""Initial Migration

Revision ID: 8e0d2827d180
Revises: c04ff50a7844
Create Date: 2019-02-28 15:47:02.357189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0d2827d180'
down_revision = 'c04ff50a7844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'upvote')
    op.drop_column('pitch', 'downvote')
    # ### end Alembic commands ###
